# Generated by Django 3.0.5 on 2021-10-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20201209_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='attempts',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
