# Generated by Django 3.0.5 on 2021-10-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_course_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='attempts',
        ),
        migrations.AddField(
            model_name='course',
            name='next_attempt',
            field=models.BooleanField(default=False),
        ),
    ]
