# Generated by Django 3.0.5 on 2021-10-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_auto_20211019_0643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='next_attempt',
            field=models.BooleanField(default=True),
        ),
    ]
