# Generated by Django 3.0.5 on 2021-10-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_auto_20211019_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='timer',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
