# Generated by Django 3.0.5 on 2021-10-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_course_end_timer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='end_timer',
        ),
        migrations.AlterField(
            model_name='course',
            name='timer',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
