# Generated by Django 3.0.5 on 2021-10-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_auto_20211019_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='end_timer',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='timer',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
