# Generated by Django 3.0.5 on 2021-10-19 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_auto_20211019_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='end_timer',
        ),
        migrations.AlterField(
            model_name='course',
            name='timer',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
