# Generated by Django 3.0.5 on 2021-10-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_auto_20211019_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='timer',
            field=models.DurationField(default='00:00:00'),
        ),
    ]
