# Generated by Django 3.0.5 on 2021-10-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_remove_course_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='timer',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
