# Generated by Django 3.0.5 on 2021-10-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_course_timer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='timer',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
