# Generated by Django 3.0.5 on 2021-10-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0018_auto_20211019_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='timer',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
