# Generated by Django 3.0.5 on 2021-10-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0019_auto_20211019_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='timer',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
