# Generated by Django 3.0.5 on 2021-10-19 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0020_auto_20211019_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='timer',
            new_name='end_timer',
        ),
    ]
