# Generated by Django 3.0.5 on 2021-10-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0021_auto_20211019_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='end_timer',
        ),
        migrations.AddField(
            model_name='course',
            name='timer',
            field=models.PositiveIntegerField(default=2, help_text='In Minutes'),
        ),
    ]
