# Generated by Django 3.0.5 on 2021-10-20 10:46

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0024_notices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notices',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
    ]
