# Generated by Django 3.0.5 on 2021-10-20 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0026_auto_20211020_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notices',
            name='title',
        ),
        migrations.AddField(
            model_name='notices',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
